export const env = "uat";
const uatBaseUrl = "https://uatapi.maxlifeinsurance.com/hris";
const prodBaseUrl = "";
const COGNITO_BASE_URL_UAT = 'https://nonprodservice.auth.ap-south-1.amazoncognito.com';
const COGNITO_BASE_URL_PROD = '';
const CLIENT_ID_UAT = '42tukg87arpovg7egqa3r5hmdc';
const CLIENT_SECRET_UAT = '13evm1c9e4p4gtaoiaga6s10921uc6q5q4jn4kpim9oknk7jdagf';
const CLIENT_ID_PROD = '';
const CLIENT_SECRET_PROD = '';
const X_API_KEY_UAT = '4iNbPS8RzT4G9q7tBp3QZ36FwFBd5GhX6Lrl4oVK';
const X_API_KEY_PROD = '';
const ENCRYPT_KEY_VALUE_UAT = "09876543345678900987654334567890";
const ENCRYPT_IV_VALUE_UAT = "0987654334567890";
const ENCRYPT_KEY_VALUE_PROD = "your-32-byte-key-here";
const ENCRYPT_IV_VALUE_PROD = "your-16-byte-iv-here";
export const X_API_KEY = env === "uat" ? X_API_KEY_UAT : X_API_KEY_PROD;
export const baseUrl = env === "uat" ? uatBaseUrl : prodBaseUrl;
export const COGNITO_BASE_URL= env === "uat" ? COGNITO_BASE_URL_UAT : COGNITO_BASE_URL_PROD;
export const CLIENT_ID = env === "uat" ? CLIENT_ID_UAT : CLIENT_ID_PROD;
export const CLIENT_SECRET = env === "uat" ? CLIENT_SECRET_UAT : CLIENT_SECRET_PROD;
export const WEBSOCKET_BASE_URL = 'wss://rb0rtd86jb.execute-api.ap-south-1.amazonaws.com/uat/?userId=';
export const ENCRYPT_KEY_VALUE = env === "uat" ? ENCRYPT_KEY_VALUE_UAT : ENCRYPT_KEY_VALUE_PROD;
export const ENCRYPT_IV_VALUE_ = env=== "uat" ? ENCRYPT_IV_VALUE_UAT : ENCRYPT_IV_VALUE_PROD;
