import apiCall from "../axiosRequest";
import { CHAT_HISTORY } from "../apiUrls";
import { baseUrl } from "../../constants/constants";

const dummyresponse = {
  status: "success",
  statusCode: 200,
  message: "Messages retrieved successfully.",
  data: {
    content: [
      {
        id: 1,
        userId: "user123",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg001",
        messageTo: "USER",
        text: "Checking bot the messages",
        replyToMessageId: null,
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1643700000.0,
      },
      {
        id: 2,
        userId: "user234",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg002",
        messageTo: "BOT",
        text: "hello",
        replyToMessageId: "msg001",
        status: "READ",
        emoji: "👍",
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1643750000.0,
      },
      {
        id: 3,
        userId: "user123",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg003",
        messageTo: "USER",
        text: "How can I help you today?",
        replyToMessageId: "msg002",
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1643800000.0,
      },
      {
        id: 4,
        userId: "user234",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg004",
        messageTo: "BOT",
        text: "Can you show me the news?",
        replyToMessageId: "msg003",
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1643859200.0,
      },
      {
        id: 5,
        userId: "user123",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg005",
        messageTo: "USER",
        text: "Here are the top news for today.",
        replyToMessageId: "msg004",
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1743955000.0,
      },
      {
        id: 6,
        userId: "user123",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg006",
        messageTo: "USER",
        text: "What time is it?",
        replyToMessageId: "msg005",
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1743950000.0,
      },
      {
        id: 7,
        userId: "user234",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg007",
        messageTo: "BOT",
        text: "Can you tell me the weather?",
        replyToMessageId: "msg006",
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1744000000.0,
      },
      {
        id: 8,
        userId: "user123",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg008",
        messageTo: "USER",
        text: "The weather today is sunny with a high of 25°C.",
        replyToMessageId: "msg007",
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1844050600.0,
      },
      {
        id: 9,
        userId: "user234",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg009",
        messageTo: "BOT",
        text: "Thanks!",
        replyToMessageId: "msg008",
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1844309200.0,
      },
      {
        id: 10,
        userId: "user123",
        email: "user123@gmail.com",
        sendType: null,
        messageType: null,
        messageId: "msg010",
        messageTo: "USER",
        text: "You're welcome! Let me know if you need anything else.",
        replyToMessageId: "msg009",
        status: "READ",
        emoji: null,
        action: "SELECTED",
        media: { video: null, image: null, document: null },
        options: null,
        botOptions: true,
        platform: "mspace",
        createdAt: 1845827200.0,
      },
    ],
    pageable: {
      pageNumber: 0,
      pageSize: 20,
      sort: {
        empty: true,
        unsorted: true,
        sorted: false,
      },
      offset: 0,
      unpaged: false,
      paged: true,
    },
    last: true,
    totalElements: 10,
    totalPages: 1,
    size: 10,
    number: 0,
    sort: {
      empty: true,
      unsorted: true,
      sorted: false,
    },
    first: true,
    numberOfElements: 10,
    empty: false,
  },
};

export const fetchChatHistory = async (agentId, page = 0, size = 10,token) => {

  try {
    const response = await apiCall({
      baseURL: baseUrl,
      url: CHAT_HISTORY,
      method: "POST",
      headers: {
         'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`,
        'x-api-key':'4iNbPS8RzT4G9q7tBp3QZ36FwFBd5GhX6Lrl4oVK'
      },
      data: { agentId: agentId, page: page, size: size },
    });

    console.log(JSON.stringify(response), " chathistory   response");
    return response?.data?.content || [];
    
  } catch (error) {
    console.error("Error fetching chat history:", error);
    
  }
};
